version: '3'
$schema: '.config\taskfile_schema.json'
vars:
  BARE_REPOS:
    - dir_name: repos/.mello-workspace.git
      remote_url: https://github.com/voltaire-toledo/Mello-Workspace.git
      release_branch: main
    - dir_name: repos/.mws-plugin-chime.git
      remote_url: https://github.com/voltaire-toledo/MWS-Plugin-Chime.git
      release_branch: main
tasks:
  default:
    desc: "Default task: list available tasks"
    silent: true                                                              # Suppress output for the default task
    cmds:
      - task: list
  list:
    desc: List available tasks
    silent: true                                                              # Suppress output for the default task
    cmds:
      - |
        echo " # List of Available tasks #"
        echo " ╭──────────────────────────────────────────────────────────────╮"
        echo " │ - task init-dev-env: Initialize development environment      │"
        echo " │ - task list: List available tasks                            │"
        echo " ╰──────────────────────────────────────────────────────────────╯"    
  init-dev-env:
    desc: Initialize development environment
    cmds:
      - mkdir -p repos/fix repos/feat repos/lab repos/refac
      - git clone --bare https://github.com/voltaire-toledo/Mello-Workspace.git repos/.mello-workspace.git
      - git clone --bare https://github.com/voltaire-toledo/MWS-Plugin-Chime.git repos/.mws-plugin-chime.git
      - git -C repos/.mello-workspace.git worktree add ../.main/Mello-WS main
      - git -C repos/.mws-plugin-chime.git worktree add ../.main/chime main
  show-color-codes:
    desc: Show color codes
    silent: true                                                              # Suppress output for the default task
    cmds:
      - |
        printf '\033[32mThis is green text\033[0m\n'
        printf '\033[34mThis is blue text\033[0m\n'
        printf '\033[43mThis has a yellow background\033[0m\n'
        printf '\033[1mThis is bold text\033[0m\n'
